site_name: Active Directory Course
site_url: https://choquitofrito.github.io/ActiveDirectory
repo_url: https://github.com/choquitofrito/ActiveDirectory
repo_name: choquitofrito/ActiveDirectory



# Configuración para archivos estáticos (diagramas)
extra_css:
  - stylesheets/extra.css

# Incluir archivos estáticos desde la carpeta diagrams
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/choquitofrito/ActiveDirectory

# Configuración para archivos estáticos
docs_dir: docs
site_dir: site

# Plugins para manejar archivos estáticos
plugins:
  - search
  - material

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
  navigation:
    collapse: true

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - admonition


nav:
  - Home: index.md
  - Windows Server:
      - "Chapitre 1.Introduction et installation de Windows Server": Chapitre 1.Introduction et installation de Windows Server.md
      - "Chapitre 2.Installation-Windows-Server-2022-VirtualBox": Chapitre 2.Installation-Windows-Server-2022-VirtualBox.md
  - DNS:
      - "Chapitre 3.DNS": Chapitre 3.DNS.md
      - "Chapitre 4.DNS-Pratique-avec-AD": Chapitre 4.DNS-Pratique-avec-AD.md
  - Active Directory:
      - "Chapitre 4.Active Directory Domain Services (AD DS)": Chapitre 4.Active Directory Domain Services (AD DS).md
      - "Chapitre 5.Unites_Organisation": Chapitre 5.Unites_Organisation.md
      - "Chapitre 6.Gestion_des_Utilisateurs": Chapitre 6.Gestion_des_Utilisateurs.md
      - "Chapitre 7.Group Policy Objects": Chapitre 7.Group Policy Objects.md
  - PowerShell:
      - "Chapitre 8.0.Powershell AD - Introduction": Chapitre 8.0.Powershell AD - Introduction.md
      - "Chapitre 8.1.Powershell AD - Concepts base": Chapitre 8.1.Powershell AD - Concepts base.md
      - "Chapitre 8.2.Powershell AD - Requetes_et_Informations": Chapitre 8.2.Powershell AD - Requetes_et_Informations.md
      - "Chapitre 8.3.Powershell AD - Creation_et_Modification": Chapitre 8.3.Powershell AD - Creation_et_Modification.md
  - Labs et Exercices:
      - "Exercices: Gestion_des_Utilisateurs": "Labo et Exercices/Exercices: Gestion_des_Utilisateurs.md"
      - "Exercices: GPO-1": "Labo et Exercices/Exercices: GPO-1.md"
      - "Exercices: GPO-2": "Labo et Exercices/Exercices: GPO-2.md"
      - "Exercices: GPO-3": "Labo et Exercices/Exercices: GPO-3.md"
      - "Exercices: OUs_Departements_Complementaires": "Labo et Exercices/Exercices: OUs_Departements_Complementaires.md"
      - "Exercices: Questions Base": "Labo et Exercices/Exercices: Questions Base.md"
      - Labo:
          - "Labo_structure": "Labo et Exercices/Labo/Labo_structure.md"
          - "Annexe.Permissions": "Labo et Exercices/Labo/Annexe.Permissions.md"
          - PowerShell Scripts:
              - "creation_structure": "Labo et Exercices/Labo/PowerShell-scriptsStructure/creation_structure.md"
              - "suppression_structure": "Labo et Exercices/Labo/PowerShell-scriptsStructure/suppression_structure.md"
  - Références: Théorie DNS- DNS Concepts Avances (Reference).md