@startuml
skinparam defaultTextAlignment center
skinparam monochrome true

rectangle "computerelectronics.be" as root {
    rectangle "comptabilite.computerelectronics.be" as compta {
        rectangle "pc01.comptabilite.computerelectronics.be" as pc1
        rectangle "printer01.comptabilite.computerelectronics.be" as printer1
    }
    
    rectangle "rh.computerelectronics.be" as rh {
        rectangle "pc01.rh.computerelectronics.be" as pc2
        rectangle "scanner01.rh.computerelectronics.be" as scanner1
    }
}

root --> compta
root --> rh
compta --> pc1
compta --> printer1
rh --> pc2
rh --> scanner1

@enduml
